### ISSUE TITLE
[Bug]: Setting Cluster.spec.imagePullSecrets after the Cluster has been created paralyzes CNPG

### ISSUE THREAD

**Issue by niels-hb** [cloudnative-pg/cloudnative-pg#8370]
### Is there an existing issue already for this bug?

- [x] I have searched for an existing issue, and could not find anything. I believe this is a new bug.

### I have read the troubleshooting guide

- [x] I have read the troubleshooting guide and I think this is a new bug.

### I am running a supported version of CloudNativePG

- [x] I have read the troubleshooting guide and I think this is a new bug.

### Version

1.26 (latest patch)

### What version of Kubernetes are you using?

1.33

### What is your Kubernetes environment?

Self-managed: k3s

### How did you install the operator?

Helm

### What happened?

Steps to reproduce:
1. Create a CNPG Cluster without image pull secrets (`imagePullSecrets: []`).
2. Wait for the Cluster to be healthy.
3. Update the Cluster CR to include at least one image pull secret.
4. The CNPG Operator will be unable to update the cluster as it tries to update the Pod in-place, which Kubernetes won't allow as `Pod.spec.imagePullSecrets` is immutable.
5. Manually deleting all (Replica + Primary) CNPG Cluster Pods fixes the issue (as this results in the recreation of Pods).
6. Manually deleting the Replica Pods does not work as the CNPG Operator will try to update the Primary first regardless.
7. Fixing the issue therefore results in reduced availability/downtime as the CNPG Operator does not launch new replicas for the Cluster until all Pods have been deleted manually.

The correct strategy needs to be a recreation of the Pods, starting with the replicas, then promoting a newly created replica Pod to the primary and finally recreating the Pod of the previous primary instance.

### Cluster resource

```shell
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  annotations:
    cnpg.io/hibernation: "off"
  name: cnpg-cluster
  namespace: default
spec:
  [...]
  imageName: mirror.example.com/ghcr.io/cloudnative-pg/postgresql:15
  imagePullPolicy: IfNotPresent
  imagePullSecrets:
  - name: regcred
  instances: 2
[...]
```

### Relevant log output

```shell
{"name":"cnpg-cluster","namespace":"default"},"namespace":"default","name":"cnpg-cluster","reconcileID":"029b6877-44aa-4e4c-afa9-a8727f501ce1","error":"cannot updated metadata on pods: Pod \"cnpg-cluster-1\" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`,`spec.initContainers[*].image`,`spec.activeDeadlineSeconds`,`spec.tolerations` (only additions to existing tolerations),`spec.terminationGracePeriodSeconds` (allow it to be set to 1 if it was previously negative)\n  core.PodSpec{\n  \t... // 11 identical fields\n  \tNodeName:         \"database-2\",\n  \tSecurityContext:  &{RunAsUser: &26, RunAsGroup: &26, RunAsNonRoot: &true, FSGroup: &26, ...},\n- \tImagePullSecrets: nil,\n+ \tImagePullSecrets: []core.LocalObjectReference{{Name: \"regcred\"}},\n  \tHostname:         \"cnpg-cluster-1\",\n  \tSubdomain:        \"\",\n  \t... // 18 identical fields\n  }\n","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...[]).reconcileHandler\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:353\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...[]).processNextWorkItem\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:300\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.1\n\tpkg/mod/sigs.k8s.io/controller-runtime@v0.21.0/pkg/internal/controller/controller.go:202"}
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by lukasgabriel** [comment]
Still relevant! 🙂

**Comment by Utwo** [comment]
Still relevant!

**Comment by greenbigfrog** [comment]
I don't think this has been fixed yet. Is it possible to reopen this?

**Comment by Atoms** [comment]
Hi maintainers, adding a data point that this is still reproducible on a current release — would it be possible to reopen this issue?

I hit exactly the same behavior described in the original report: adding spec.imagePullSecrets to an already-running Cluster causes the operator to attempt an in-place Pod update, which the API server rejects because Pod.spec.imagePullSecrets is immutable. Reconciliation then stalls for the whole cluster until the Pods are deleted manually.

Environment

CloudNativePG: {"level":"info","ts":"2026-09-05T20:43:18.479836915Z","logger":"setup","msg":"Starting CloudNativePG Operator","version":"1.30.0","build":{"Version":"1.30.0","Commit":"4b5e244a7","Date":"2026-06-29"}}
Kubernetes: v1.36.2-eks-bca9cf6, EKS
Operator installed via Helm

Steps

Cluster created and healthy, no imagePullSecrets set.
Added a pull secret to spec.imagePullSecrets (moving images to a private registry).
Operator enters a reconcile error loop.

Relevant log
```
"error":"cannot updated metadata on pods: Pod \"<cluster>-1\" is invalid: spec: Forbidden: pod updates may not change fields other than `spec.containers[*].image`,`spec.initContainers[*].image`,`spec.activeDeadlineSeconds`,`spec.tolerations` (only additions to existing tolerations),`spec.terminationGracePeriodSeconds` (allow it to be set to 1 if it was previously negative)
@@ -681,7 +681,11 @@
- "ImagePullSecrets": null,
+ "ImagePullSecrets": [
+  {
+   "Name": "<pull-secret>"
+  }
+ ],
```
I'd agree with the original proposal: a change to imagePullSecrets should be treated like any other Pod-template change that requires recreation, i.e. rolling through the replicas first, then a switchover, then recreating the old primary — rather than attempting an in-place metadata update. Alternatively, a validating webhook rejecting the change with a clear message would at least avoid leaving the cluster in a stuck state.

Happy to provide more details or test a fix if that helps.

**Comment by gbartolini** [comment]
Reopened, thanks!

**Comment by GellertBabel** [comment]
I have a qestion about step 4 in the reproduction of the issue:  is the operator really attempting an in-place Pod update here? The failing request is cannot updated metadata on pods, which comes from ReconcileMetadata, i.e. a labels/annotations patch. I think nothing in the operator writes Pod.spec.imagePullSecrets. It only sets them on the ServiceAccount, and when a Pod really has to change it is deleted and recreated, never patched.

So the imagePullSecrets difference seems to be added to that patch during admission rather than by the operator. Does your cluster have a mutating webhook or policy that sets imagePullSecrets on pods for UPDATE as well as CREATE?

**Comment by mnencia** [comment]
PR #11521 adds a rollout for Pods that never got a pull secret added after they were created. Real gap, but not what stalls the cluster here.

The request that fails is a labels/annotations merge patch on the Pod (`pkg/reconciler/instance/metadata.go`). Its body never touches spec, and the operator never writes `Pod.spec.imagePullSecrets`, it only adds the secret to the instance ServiceAccount. Since Kubernetes 1.24 the built-in ServiceAccount admission plugin copies pull secrets into a Pod on CREATE only. On 1.33 and 1.36 the imagePullSecrets in the rejected object can therefore only come from a mutating admission webhook in the cluster.

Following up on GellertBabel's question above, one quick check settles it: run `kubectl label pod <cluster>-1 cnpg-test=1`. If that fails with the same error, the operator is not involved. Then `kubectl get mutatingwebhookconfigurations` and look for one matching pods on UPDATE.

Separately, one rejected label patch should not freeze the whole reconcile. That part is on us and is a fair follow-up, and it is also what prevents #11521's rollout from ever running in this scenario.
